### PR TITLE
when creating a WPT, also create corresponding TRKPT

### PR DESCRIPTION
**Pull request by icrf2000**
See #187 .

This new PR replaces the old #188 . I closed the latter because there were to many merge conflicts, the develop branch diverged too much since it was initially created.

### CODE REVIEW

**Comment by xsaco07** [comment]
Hi @icrf2000 this makes sense to me. Can you please rebase develop branch again? Important changes were merged. By doing this, we make sure that develop passes the Travis tests.

Thanks!

**Comment by icrf2000** [comment]
Reopening this accidentially deleted the PR.

**Comment by icrf2000** [comment]
Hi @xsaco07,

ok, done, hope it works.

**Comment by icrf2000** [comment]
...didn't work.... So I created a new PR. Please apologize my SPAM.

**Comment by xsaco07** [comment]
Don't worry that happens! Thanks for your collaboration @icrf2000

**Pull request closed without merging**
