### PR TITLE
Include the track's tags into the GPX file

### PR DESCRIPTION
**Pull request by icrf2000**
I put the track's tags into the GPX file. Format:

```
<extensions>
  <tags>
    holiday2018,bike
  </tags>
</extensions>
```
Comment: According to the GPX specification, every element inside `<extensions>` should use a private namespace, so actually it should read for example `<osmtracker:tags>` (only an example, the exact name would be up for discussion). I didn't do it because all other places in the app which use `<extensions>` also don't do it.

### CODE REVIEW

**Comment by aton1698** [comment]
Hi, thanks for your contribution! :D
Just one thing, some commits related with the PR #171 are now in this PR, could you fix that?

**Comment by icrf2000** [comment]
Oha, somewhere I lost the overview over my local branch mess and merged in something I shouldn't have merged. I (tried to) step back and apply the intended changes without polluting them with unrelated stuff. The resulting local branch name is now hz04_export_tags. It is supposed to contain the tags and description export stuff only. Problem: I don't know how to edit the existing PR to use this new branch. Maybe I have to close this PR and open a new one. I would rather avoid this to preserve the conversation history. If you don't mind, could you check whether hz04_export_tags is as you like?

**Comment by icrf2000** [comment]
I think I found a way to push the fixed hz_export_tracks (reset, cherry-pick,force-push). Tested and it seems to be ok.

**Comment by aton1698** [comment]
Thanks for all your job and contributions! 
Everythink looks ok!

**Pull request merged**
