### PR TITLE
add support for media button for android 3.0 and later

### PR DESCRIPTION
**Pull request by zdila**
add support for media button for android 3.0 and later

### CODE REVIEW

**Comment by e2jk** [comment]
This feature introduced a bug for me, where I can't use the hardware button to stop my podcast player, instead osmtracker starts up, records track #0 (which can't ever be found back), and the podcast player continues playing.

Please have a look and discuss further at https://code.google.com/p/osmtracker-android/issues/detail?id=256

**Comment by zdila** [comment]
I'll try to fix it.

**Comment by nguillaumin** [comment]
I put a few comments on https://code.google.com/p/osmtracker-android/issues/detail?id=256 with possible leads...

**Comment by e2jk** [comment]
zdila, please look at my latest post, using the test .apk that Nicolas created. Your input is needed.

**Comment by zdila** [comment]
It is on my long task list :-). Till then you can use older version.

**Comment by zdila** [comment]
I tried three different phones (Runbo X6, Sony ST21i (Xperia Tipo) and Lenovo Yoga Tablet 2) with two headphone sets (one with single button, second with three buttons).

Good news is that it works without setting priority on intent-filter.

Strange thing is that even with priority set to 1000 I was unable to reproduce reported issue with any phone or headset I listed.

I think you can close this issue.

**Pull request merged**
