### PR TITLE
Export to public directory (Fix #443, Fix #440)

### LINKED ISSUE #440: OSM Tracker GPS Export broken
As far as I can tell, since updating to `v2024.07.09`, "Export as GPX" does not appear to work. At least, the files do not appear in their normal location (I haven't changed any settings), nor in any other obvious location.

(Android version 12)

### LINKED ISSUE #443: GPX export not working
Hi.
Since F-Droid upgraded OSMTracker to 2024.07.09 (62), exporting to GPX no longer works. I get: “export process finished successfully” and the green light is shown, but no GPX file appears in the directory.
The directory was set to `/osmtracker`, I tried changing it to `/storage/emulated/0/osmtracker`, to no avail.
Android 13, LineageOS 20-20231222
Thanks in advance.

### PR DESCRIPTION
**Pull request by Zahnstocher**

### CODE REVIEW

**Review by Binnette — APPROVED** [review]
Works perfectly! TY @Zahnstocher

**Comment by Andyporras** [comment]
Hi @Zahnstocher,

I’ve reviewed the PR "Export to public directory (Fix #443, Fix #440)," and I can confirm it works perfectly in both the current version and with the updates in PR #457 (target SDK 35). Excellent work!

However, I noticed a couple of points that could be improved:

The pull request currently lacks a description. Including a brief overview of the changes and their impact would make the PR more informative for reviewers.

The exported files are being saved in the Documents directory, which isn’t reflected in the current UI message. The message still mentions “External storage (SD) directory,” which might confuse users. Updating this text to accurately reflect the export location would improve clarity and usability.

**Comment by Andyporras** [comment]
> Hi @Zahnstocher,
> 
> I’ve reviewed the PR "Export to public directory (Fix #443, Fix #440)," and I can confirm it works perfectly in both the current version and with the updates in PR #457 (target SDK 35). Excellent work!
> 
> However, I noticed a couple of points that could be improved:
> 
> The pull request currently lacks a description. Including a brief overview of the changes and their impact would make the PR more informative for reviewers.
> 
> The exported files are being saved in the Documents directory, which isn’t reflected in the current UI message. The message still mentions “External storage (SD) directory,” which might confuse users. Updating this text to accurately reflect the export location would improve clarity and usability.


To improve clarity for users, you could update this message in the file app/src/main/res/values/strings-preferences.xml, specifically on line 76, to reflect the correct export location. If you’d like, I can take care of making this change for you—just let me know!

Best regards.

**Comment by Binnette** [comment]
Hi @Andyporras, about the string in file "strings-preferences.xml" line 76. I would set this string simply to "Public directory". Tell me if you're good with this or propose me something else 👍

**Pull request merged**
