### PR TITLE
Scrollview available layouts

### PR DESCRIPTION
**Pull request by Binnette**
Add a simple scrollview to make the "Available layouts" view scrollable. Yes there are too much buttons for my screen.

https://github.com/user-attachments/assets/78c2d949-9532-480d-9728-7a4a4d688568

### CODE REVIEW

**Comment by Binnette** [comment]
Hi @jamescr, If needed, you can add me as repo maintainer. I will be happy to review, test and merge the PR. And also triage bug and so on. I am developer and did Android development as well.
For more info, feel free to visit my GitHub Profile or [Osm Profile](https://www.openstreetmap.org/user/Binnette).

**Comment by Binnette** [comment]
BTW, you should merge #448 first to fix Gradle download issue in Android Studio.

**Comment by jamescr** [comment]
@Binnette could you change the target branch of the PR to develop?

**Comment by Andyporras** [comment]
Hi Binnette,

Great work on the PR “Scrollview available layouts #456.” The ScrollView implementation works seamlessly in the current version and is also fully compatible with the changes in PR #457 (target SDK 35). It’s an effective solution for handling screens with a large number of buttons.

However, as per @jamescr  comment, could you please change the target branch of this PR from master to develop? This will ensure smoother integration and alignment with the project's workflow.

**Pull request merged**
